---
# tasks file for ansible-roles-sshd
- name: Create backup
  copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.{{ ansible_date_time.date }}
    remote_src: yes
    force: no
- name: Modify sshd_settings
  lineinfile: 
    path: '/etc/ssh/sshd_config'
    regexp: '{{item.pattern}}' 
    line: '{{item.line_value}}' 
    insertafter: '{{item.insertafter}}'
  with_items:
    - { pattern: '^Port.*', line_value: 'Port {{ sshd_port }}', insertafter: '^#Port.*' }
    - { pattern: '^PermitRootLogin yes', line_value: 'PermitRootLogin no', insertafter: ^#PermitRootLogin yes}
    - { pattern: '^AllowUsers.*', line_value: 'AllowUsers {{ sshd_user }}', insertafter: EOF}
  notify:
    - restart_sshd
